/**
 * Shared domain types — the single source of truth for the shapes that flow
 * between the DB (Prisma `Json` columns), the API routes, the Pyodide worker,
 * and the React UI. Keeping them here prevents drift across those boundaries.
 *
 * The DB stores these as untyped `Json`; helpers in `lib/problem.ts` cast the
 * raw Prisma rows into these typed views.
 */

import type { Tag } from "./tags";

// ---------------------------------------------------------------------------
// Enumerations (stored as strings so the schema stays SQLite/Postgres portable)
// ---------------------------------------------------------------------------

export type ProblemType = "debug" | "review" | "design";
export type Difficulty = "easy" | "medium" | "hard";
export type Severity = "critical" | "major" | "minor";

export const PROBLEM_TYPES: ProblemType[] = ["debug", "review", "design"];
export const DIFFICULTIES: Difficulty[] = ["easy", "medium", "hard"];

// ---------------------------------------------------------------------------
// Answer key — the ground truth the generator seeds (spec §2, §11).
// Grading matches a user's fixes/comments against these known issues.
// ---------------------------------------------------------------------------

export interface AnswerKeyIssue {
  /** Stable id, referenced by the grade breakdown. */
  id: string;
  /** File the issue lives in (review: the diff file path; debug: informational). */
  file?: string;
  /** 1-based inclusive line range in the starter code / diff the issue lives on. */
  lineStart: number;
  lineEnd: number;
  severity: Severity;
  /** The concrete failure this flaw causes (what breaks, for whom). */
  failure: string;
  /** The reasoning a strong reviewer would give — shown in results + used for grading. */
  explanation: string;
  /** Lowercased keywords/synonyms that signal the user identified this issue. */
  keywords: string[];
}

// ---------------------------------------------------------------------------
// Debug mode — Pyodide-executed test suite (spec §9, §11.4)
// ---------------------------------------------------------------------------

export interface TestCase {
  /** Test function name, e.g. "test_partial_last_batch". */
  name: string;
  /** Python source for this test; asserts against the user's solution. */
  body: string;
}

export interface TestSuite {
  /** Optional Python run before the tests (imports the project, fixtures, data). */
  setup?: string;
  cases: TestCase[];
}

/**
 * One file in a multi-file project (spec: real-world problems span a package,
 * not a single script). For debug, these are the editable source files; the
 * test suite imports them by module path. `readOnly` files (fixtures, configs,
 * neighbouring modules the user shouldn't touch) render but can't be edited.
 */
export interface SolutionFile {
  /** Path relative to the project root, e.g. "batcher/core.py". */
  path: string;
  content: string;
  readOnly?: boolean;
}

// ---------------------------------------------------------------------------
// Review mode — structured unified diff (spec §10)
// ---------------------------------------------------------------------------

export type DiffLineKind = "context" | "add" | "del";

export interface DiffLine {
  kind: DiffLineKind;
  /** Line number in the *new* file (null for deleted lines). This is the
   *  coordinate system the answer key + user comments anchor to. */
  lineNo: number | null;
  content: string;
}

export interface DiffHunk {
  /** File path shown in the diff header. */
  file: string;
  lines: DiffLine[];
}

export interface PrMeta {
  number: number;
  branch: string;
  additions: number;
  deletions: number;
  files: number;
  /** Whether the PR is flagged as AI-generated (it always is, in v1). */
  aiGenerated: boolean;
}

// ---------------------------------------------------------------------------
// Problem — the client-facing, typed view of a bank row
// ---------------------------------------------------------------------------

export interface Problem {
  id: string;
  type: ProblemType;
  language: string;
  difficulty: Difficulty;
  title: string;
  prompt: string;
  jdContext: string | null;
  starterCode: string | null; // legacy single-file; `files` supersedes it
  files: SolutionFile[] | null; // debug: the editable multi-file project
  diff: DiffHunk[] | null;
  prMeta: PrMeta | null;
  testSuite: TestSuite | null;
  rubric: RubricDimension[] | null;
  answerKey: AnswerKeyIssue[];
  qualityScore: number | null;
  source: "authored" | "generated";
  /** Which model wrote this problem (null for hand-authored seeds). INV-11. */
  generatorModel: string | null;
  /** The GenerationJob that produced it, when generated by the worker tier. */
  sourceJobId: string | null;
  /** Fixed-vocabulary topic tags driving JD match-first (see lib/tags.ts). */
  tags: Tag[];
  upvotes: number;
  downvotes: number;
  timesAttempted: number;
  retired: boolean;
}

/**
 * The problem as sent to the browser while solving.
 *
 * Three fields are withheld, and each omission is load-bearing:
 * - `answerKey` — ground truth; grading happens server-side against it (INV-1).
 * - the *count* of answer-key entries — telling the user how many flaws were
 *   planted turns the exercise into a scavenger hunt with a known terminating
 *   condition, which is not the skill being trained (INV-9).
 * - `jdContext` — the pasted job description may carry a real company's
 *   internal role details, and problems are served from a shared bank, so it
 *   must never reach a client other than its author's (INV-12).
 */
export type PublicProblem = Omit<Problem, "answerKey" | "jdContext">;

/** Compact row for the bank list, with the curation signals the UI shows. */
export interface ProblemSummary {
  id: string;
  type: ProblemType;
  title: string;
  difficulty: Difficulty;
  upvotes: number;
  downvotes: number;
  timesAttempted: number;
  /** Human quality label derived from votes (see lib/curation.ts). */
  quality: "good" | "mixed" | "new";
}

// ---------------------------------------------------------------------------
// Design mode (phase 2) — rubric
// ---------------------------------------------------------------------------

export interface RubricDimension {
  id: string;
  name: string;
  description: string;
  weight: number;
}

// ---------------------------------------------------------------------------
// Execution — the Pyodide worker protocol (spec §9)
// ---------------------------------------------------------------------------

/** Sent from the main thread to the worker. */
export interface RunRequest {
  userCode: string;
  /** Python harness that imports the user's solution and runs the test cases,
   *  emitting a JSON result via a sentinel (see lib/pyodide/harness.ts). */
  testCode: string;
}

/** Result of a single test case after execution. */
export interface TestResult {
  name: string;
  passed: boolean;
  /** Assertion / error detail shown when the case fails. */
  message?: string;
}

/** Sent from the worker back to the main thread. */
export interface RunResult {
  ok: boolean;
  /** Combined stdout + stderr captured during the run. */
  output: string;
  /** Structured per-test outcomes (empty if the code crashed before tests ran). */
  tests: TestResult[];
  /** Top-level error message (syntax error, timeout, uncaught exception). */
  error?: string;
  /** True when the run was killed by the watchdog timeout. */
  timedOut?: boolean;
}

/** One recorded run, persisted to Attempt.runHistory for approach grading. */
export interface RunRecord {
  passed: number;
  failed: number;
  output: string;
  at: number;
}

// ---------------------------------------------------------------------------
// Submissions & grading (spec §12, §15)
// ---------------------------------------------------------------------------

/** A line comment the user leaves during review. */
export interface ReviewComment {
  /** File path the comment is on (matches DiffHunk.file). Optional for
   *  single-file back-compat; multi-file problems always set it. */
  file?: string;
  /** Line number in the new file (matches DiffLine.lineNo). */
  line: number;
  body: string;
}

export type Submission =
  | { mode: "debug"; files: SolutionFile[]; runHistory: RunRecord[] }
  | { mode: "review"; comments: ReviewComment[] }
  | { mode: "design"; doc: string };

/** How a single seeded issue fared against the user's submission. */
export interface IssueOutcome {
  issueId: string;
  status: "caught" | "missed";
  /** Severity of the underlying seeded issue (shown as a chip in results). */
  severity?: Severity;
  /** Short label of the issue's failure. */
  failure: string;
  explanation: string;
  /** For caught issues: what the user said that matched. */
  matchedOn?: string;
}

/** A user comment/claim that didn't correspond to any seeded issue. */
export interface FalsePositive {
  line?: number;
  body: string;
  /** Model's short note on why it isn't a real issue (review mode). */
  note?: string;
}

/** One component of the score, so the results screen can show *how* the
 *  number was arrived at instead of a prose 'formula' paragraph. Sum of
 *  `earned` equals the overall `score`. Grader is the source of truth. */
export interface ScoreLine {
  /** Short label, e.g. 'Tests pass', 'Approach quality', 'Issues caught'. */
  label: string;
  /** Points earned on this component (already weighted). */
  earned: number;
  /** Points available on this component. Sum of `max` across lines is 100. */
  max: number;
  /** Optional detail rendered next to the number (e.g. '2/3 issues'). */
  detail?: string;
}

export interface Grade {
  /** 0–100 overall score. */
  score: number;
  /** One-line verdict headline shown on the results screen. */
  headline: string;
  summary: string;
  outcomes: IssueOutcome[];
  falsePositives: FalsePositive[];
  /** Component-by-component score breakdown, shown on the results screen. */
  breakdown: ScoreLine[];
  /**
   * Which model produced the judgments this score was assembled from (INV-11).
   * The score is assembled in code, but every mode feeds it model-supplied
   * inputs — false-positive verdicts in review, `approachScore` in debug (45%
   * of the number), the whole rubric read in design. Recording the judge is
   * what makes a stored Attempt re-gradable and comparable across routings.
   */
  graderModel?: string;
  /** Debug only: did the objective test suite pass on the final submission. */
  testsPassed?: boolean;
  /** Design only (phase 2): per-dimension scores. */
  dimensionScores?: { name: string; score: number; justification: string }[];
}

// ---------------------------------------------------------------------------
// Socratic follow-up chat (spec §5, §12)
// ---------------------------------------------------------------------------

export type ChatRole = "interviewer" | "user";

export interface ChatMessage {
  role: ChatRole;
  content: string;
}
